### ISSUE TITLE
Better Settings for Vscode

### ISSUE THREAD

**Issue by LucaBecherini** [Lxlp38/MythicScribe#2]
I open files on a remote server, so I can't easily verify the folder where the file is located because it's a temporary file on my local machine.

Additionally, I can't enable MythicScribe for all YAML files since I'm a developer, and it conflicts with some daily YAML files I work on (plus all the files also used by other plugins).

I've tried using regular expressions, but they don't seem to work correctly. All of my files end with _items, _skills, _mobs, etc., and even with common regex patterns like .*_items.*, it doesn’t seem to match.

On top of that, I usually format my files after saving them, but the extension isn't compatible with common YAML formatters, even when I manually configure the settings in settings.json.

**Comment by Lxlp38** [comment]
How are you accessing those files/with what extension? I have had  other people say how the extension worked under those conditions, so it's possible that the problem may have something to do with with your exact setup.

## File recognition problem
But in any case, for the file regex: if the regex for the MythicMobs folder is not matched, then the extension will not check for any file-specific regex. So, even if you have them set up, i think the reason they are not working for you is that the main regex is not being matched.

### Solution 1: Change `MythicScribe.regexForMythicmobsFile`
In order to make the regex match in your specific conditions *right now*, a solution may be that of using a regex like `(_items)|(_skills)|(_mobs)` for your `MythicScribe.regexForMythicmobsFile` configuration. I will think about this problem further and implement a better solution in the future, at which point I will contact you again to let you know.

### Solution 2: Make Specific Workspace
Another solution would be that of making a vscode workspace specific for mythicmobs usage and use the `MythicScribe.alwaysEnabled` config option there

### Formatting Problem
I hadn't considered the problem as I usually don't format mythicmobs files myself, has they can have a syntax not properly recognized by normal formatters (especially when it comes to inline metaskills and the likes), but i will look into it and implement it if possible

In any case! Sorry for the delay in answering the question. If you would like to have a better conversation regarding the issue you could consider joining [our discord server](https://discord.gg/UgcPG5ADDe) so we can talk there. 

Thank your for the feedback, and let me know if what i suggested can somewhat help you until I properly address the issues :D

**Comment by Lxlp38** [comment]
@LucaBecherini a Formatter was added in the [1.4.0 Release](https://github.com/Lxlp38/MythicScribe/releases/tag/v1.4.0), let me know if it helps or if you have any other feedback!
